### ISSUE TITLE
Use submodules

### ISSUE THREAD

**Issue by GravisZro** [hstarmans/hexastorm#3]
A multi-repository project like this should be using submodules.  A git submodule is like a symbolic link to a specific branch and version of a another repository.  For each iteration of the entire machine, you could have a branch with different submodules links.  This would allow someone to clone (a branch) the repository (recursively) and be sure that all the parts of the project matched.

**Comment by hstarmans** [comment]
Gravis, you are right but there are many points at which the project can be improved. So far I work on it alone and there are no collaborators. I looked out for these but a project like this takes a lot of time.
If this changes I could improve the overall delivery.  My current focus is to add the PCB motor to the project. I will improve my organization if it takes minimal effort and improves my working efficiency.
If you want to help with the PCB motor, let me know..

**Comment by GravisZro** [comment]
I was looking into possibly advancing the project but to do that, I need to be able to understand it (I couldn't find the PCB for the PCB motor at all!).  I can fix your repo issues if you can supply the information I need to properly organize it.

The information I need is really just the date (of the first git commit) of each new iteration.  I should be able to organize everything from there.

**Comment by hstarmans** [comment]
You can look into the git history to see what is currently worked on;
 The PCB for the PCB motor is shared here https://github.com/hstarmans/firestarter/tree/master/scanhead_pcb_compact
 The code for driving the board is here https://github.com/hstarmans/hexastorm/tree/master/tests/custommotor
 The CAD design is here https://github.com/hstarmans/hexastorm_design/blob/master/FreeCAD%20files/assembly_compact.FCStd
The PCB motor can spin at 3000 RPM for at least 30 minutes. I am currently trying to rotate it when it is in a vertical position. Hereafter, I hope to do tests with a laser.

**Comment by hstarmans** [comment]
@GravisZro micropython support is almost there... I think I should close this for now.
